# Site settings
title: Title Here
header-img: img/home-bg.png
email: kpeck71@gmail.com
copyright_name: kpeck71
description: > # this means to ignore newlines until "baseurl:"
  Remote part-time web development, one day at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kpeck71
learn_profile: kpeck71
email_username: kpeck71@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
